# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0c40d10e5c31a496349ec5cb92d1eb6bdadb3d4afe6dbef4c73a2bb7b3486f1db32aced0d55b09bda2fbac3389a34426e0ea12397d9449894d9de9233ec1534

test:
  secret_key_base: d4f38c583c89bdff0f1b297a15ee98829584a122c06646ef88b6da5336ccbac68df285c22a64ac48dd8cd371f1a86173284593286c2243e112dbae00805adc36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
