twitter_consumer_key_jp: (please set)
twitter_consumer_secret_jp: (please set)
twitter_oauth_token_jp: (please set)
twitter_oauth_token_secret_jp: (please set)

twitter_consumer_key_en: (please set)
twitter_consumer_secret_en: (please set)
twitter_oauth_token_en: (please set)
twitter_oauth_token_secret_en: (please set)

twitter_consumer_key_cn: (please set)
twitter_consumer_secret_cn: (please set)
twitter_oauth_token_cn: (please set)
twitter_oauth_token_secret_cn: (please set)

twitter_consumer_key_tw: (please set)
twitter_consumer_secret_tw: (please set)
twitter_oauth_token_tw: (please set)
twitter_oauth_token_secret_tw: (please set)


